[mypy]
mypy_path = .
python_version = 3.8
ignore_missing_imports = True
disallow_untyped_defs = False
no_implicit_optional = False
explicit_package_bases = True
check_untyped_defs = False
show_error_codes = True
show_column_numbers = False
warn_unused_ignores = False
warn_return_any = False

# This affects which files get analyzed at all
#exclude = '(^pyextra/|^cereal/|^rednose/|^panda/|^laika/|^opendbc/|^laika_repo/|^rednose_repo/|^\.github/misc_scripts/|^selfdrive/controls/lib/dynamic_follow/)'
#exclude = '(^pyextra/|^cereal/|^rednose/|^panda/|^laika/|^opendbc/|^laika_repo/|^rednose_repo/|^\.github/misc_scripts/|^selfdrive/controls/lib/dynamic_follow/)'
exclude = '(^pyextra/|^cereal/|^rednose/|^panda/|^laika/|^opendbc/|^laika_repo/|^rednose_repo/|.*\.github/misc_scripts/.*|^selfdrive/controls/lib/dynamic_follow/)'

# Disable mypy checking for noisy submodules (even when imported)
[mypy-pyextra.*]
ignore_errors = True

[mypy-cereal.*]
ignore_errors = True

[mypy-rednose.*]
ignore_errors = True

[mypy-panda.*]
ignore_errors = True

[mypy-laika.*]
ignore_errors = True

[mypy-opendbc.*]
ignore_errors = True

[mypy-laika_repo.*]
ignore_errors = True

[mypy-rednose_repo.*]
ignore_errors = True

[mypy-selfdrive.controls.lib.dynamic_follow.*]
ignore_errors = True

[mypy-github.*]
ignore_errors = True
