#!/usr/bin/env bash
set -euo pipefail

echo "✅ Running in bash $BASH_VERSION"

TELETYPED_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESOLV_SRC="$TELETYPED_DIR/resolv.conf"

# Targets: both can matter on Android/AGNOS-ish systems
TARGETS=(
  "/etc/resolv.conf"
  "/system/etc/resolv.conf"
)

write_hardened_resolv() {
  echo "[+] Writing hardened resolv.conf to: $RESOLV_SRC"
  cat > "$RESOLV_SRC" <<'EOF'
# Autogenerated by teletyped/setup_resolv.sh
# Multiple resolvers to survive local DNS failures / flaky upstreams
# rotate makes libc try different servers over time

nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 9.9.9.9
nameserver 8.8.4.4

options timeout:2 attempts:2 rotate
EOF
  chmod 600 "$RESOLV_SRC" 2>/dev/null || true
}

# Ensure source exists and is "ours"
if [ ! -f "$RESOLV_SRC" ] || ! grep -q "Autogenerated by teletyped/setup_resolv.sh" "$RESOLV_SRC" 2>/dev/null; then
  write_hardened_resolv
else
  echo "[=] teletyped/resolv.conf already hardened"
fi

# Remount /system writable temporarily (if present)
if [ -d /system ]; then
  echo "[+] Remounting /system rw"
  mount -o rw,remount /system >/dev/null 2>&1 || true
fi

# Ensure targets exist
for t in "${TARGETS[@]}"; do
  if [ ! -e "$t" ]; then
    echo "[+] Creating $t"
    mkdir -p "$(dirname "$t")" >/dev/null 2>&1 || true
    : > "$t"
    chmod 600 "$t" 2>/dev/null || true
  fi
done

# Helper: is path a mountpoint? (robust, doesn't rely on 'mount' output)
is_mountpoint() {
  local p
  p="$(readlink -f "$1" 2>/dev/null || echo "$1")"
  # mountinfo has: ... <mountpoint> ...
  # ensure we match the mountpoint column with surrounding spaces
  grep -q " $p " /proc/self/mountinfo 2>/dev/null
}

# Bind-mount resolv.conf onto targets
for t in "${TARGETS[@]}"; do
  if is_mountpoint "$t"; then
    echo "[!] $t is already a mountpoint; unmounting first"
    umount "$t" >/dev/null 2>&1 || true
  fi

  echo "[+] Bind-mounting $RESOLV_SRC -> $t"
  # Silence output to avoid toybox/busybox 'Broken pipe' noise
  mount --bind "$RESOLV_SRC" "$t" >/dev/null 2>&1 || true

  # Verify content
  if ! grep -q "Autogenerated by teletyped/setup_resolv.sh" "$t" 2>/dev/null; then
    echo "[!] Warning: $t does not contain expected content after mount"
  fi
done

# Remount /system read-only again
if [ -d /system ]; then
  echo "[+] Remounting /system ro"
  mount -o ro,remount /system >/dev/null 2>&1 || true
fi

echo "[✅] DNS configured."

echo "[i] Active contents:"
echo "----- $RESOLV_SRC"
sed -n '1,120p' "$RESOLV_SRC" 2>/dev/null || true
echo "----- /etc/resolv.conf"
sed -n '1,120p' /etc/resolv.conf 2>/dev/null || true
echo "----- /system/etc/resolv.conf"
sed -n '1,120p' /system/etc/resolv.conf 2>/dev/null || true

echo "[i] mountinfo (best-effort):"
grep -E " /etc/resolv\.conf | /system/etc/resolv\.conf " /proc/self/mountinfo 2>/dev/null || true

echo "[i] inode check (if inodes match, it’s truly the same file view):"
ls -li "$RESOLV_SRC" /etc/resolv.conf /system/etc/resolv.conf 2>/dev/null || true

